# Generated by Django 2.1 on 2018-09-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='empty_places',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='places',
            field=models.IntegerField(default=10),
        ),
    ]
