# Generated by Django 2.1.3 on 2018-12-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=140)),
                ('course_price', models.IntegerField()),
                ('course_date_1', models.DateTimeField()),
                ('course_date_2', models.DateTimeField()),
                ('places', models.IntegerField(default=10)),
                ('empty_places', models.IntegerField(default=0)),
            ],
        ),
    ]
