# Generated by Django 2.1.3 on 2018-12-01 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=' ', max_length=250)),
                ('date', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField(default=0, help_text='Number of exercise on E-Olymp')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default=' ', max_length=150)),
                ('author_code', models.TextField(default=' ', verbose_name='Solution')),
                ('date', models.DateTimeField(auto_now=True)),
                ('code_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.Code', verbose_name='Related exercise')),
            ],
        ),
    ]
