# Generated by Django 2.1.1 on 2018-10-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Share', '0002_auto_20181003_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
