# Generated by Django 2.1.1 on 2018-10-09 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Share', '0003_auto_20181003_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default=' ', max_length=150)),
                ('author_code', models.TextField(default=' ')),
                ('date', models.DateTimeField(auto_now=True)),
                ('code_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Share.Code')),
            ],
        ),
    ]
