# Generated by Django 2.1.1 on 2018-10-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Share', '0005_remove_code_source_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='number',
            field=models.IntegerField(default=0, help_text='Number of exercise on E-Olymp'),
        ),
    ]
